### ISSUE TITLE
Upload logo didn't show

### ISSUE THREAD

**Issue by chuckyuee** [spree/spree_rails_frontend#67]
in app/helpers/spree/frontend_helper.rb line 11-31

```
    def logo(image_path = nil, options = {})
      logo_attachment = if defined?(Spree::StoreLogo) && current_store.logo.is_a?(Spree::StoreLogo)
                          current_store.logo.attachment # Spree v5
                        else
                          current_store.logo # Spree 4.x
                        end

      image_path ||= if logo_attachment&.attached? && logo_attachment&.variable?
                       main_app.cdn_image_url(logo_attachment.variant(resize_to_limit: [244, 104]))
                     elsif logo_attachment&.attached? && logo_attachment&.image?
                       main_app.cdn_image_url(logo_attachment)
                     else
                       asset_path('logo/spree_50.png')
                     end

      path = spree.respond_to?(:root_path) ? spree.root_path : main_app.root_path

      link_to path, 'aria-label': current_store.name, method: options[:method] do
        image_tag image_path, alt: current_store.name, title: current_store.name
      end
    end
```

Change blow this line code:

'''
main_app.cdn_image_url(logo_attachment.variant(resize_to_limit: [244, 104])
'''

Rails 7.1.3 it's works.

**Comment by damianlegawiec** [comment]
> Ran into this very issue today. Is the fix expected in a new version? I can see it is in master, but it isn't in the 4.8.0 release and no amount of bundle updating wilfully forcing it. Are we to use the main branch for now?

Hi @code-bunny 

We're currently working on a new, modern, themes-supported storefront - https://github.com/spree/spree/issues/12182- part of the Spree 5 release (early next year).

I recommend using the main branch of this repo for now, as our focus is on that new storefront. We do accept community patches/fixes for this one

**Comment by code-bunny** [comment]
@damianlegawiec thanks for the update. I did spy the work was being done for Spree 5, sadly the current store is on Ruby 2.7.8 and Spree 3.7 and falling apart at the seams so I need to update it right now. Which by the sounds of it means we'll upgrade to 4.10 just in time for all 5.0 to roll in. 

We'll use the master branch for now.
