### ISSUE TITLE
Coupon codes with a dot or % symbol can't be removed from cart

### ISSUE THREAD

**Issue by zavan** [spree/spree_rails_frontend#76]
## Context

If you create a coupon with a "." or a "%" in the code it can't be removed from the cart and you get stuck with it, even if you try to reset it by clearing the cart.

This is because [Rails doesn't allow these characters by default in route params](https://guides.rubyonrails.org/routing.html#dynamic-segments):

> By default, dynamic segments don't accept dots - this is because the dot is used as a separator for formatted routes. If you need to use a dot within a dynamic segment, add a constraint that overrides this – for example, id: /[^\/]+/ allows anything except a slash.

## Expected Behavior
It should remove the coupon, or at least validate in the admin that coupon codes can't be created with these characters.

## Actual Behavior
The API throws a 422 error and the coupon stays in the cart.

## Possible Fix
I fixed this by overriding the route constraint in my routes:

```ruby
Rails.application.routes.draw do
  delete '/api/v2/storefront/cart/remove_coupon_code/:coupon_code',
    to: 'spree/api/v2/storefront/cart#remove_coupon_code',
    as: :cart_remove_coupon_code,
    constraints: { coupon_code: /[^\/]+/ } # Allow any char but slashes

  mount Spree::Core::Engine, at: '/'
end
```

And properly encoding the coupon code param in `vendor/assets/javascripts/spree/frontend/all.js`:

```js
Spree.routes.api_v2_storefront_cart_remove_coupon_code = (couponCode) => {
  return Spree.localizedPathFor(`api/v2/storefront/cart/remove_coupon_code/${encodeURIComponent(couponCode)}`)
}
```

If you don't encode it, something like "COUPON20%" would make nginx throw an error 400.

## Your Environment

Rails v7.1.3.4 and Spree v4.8.3

**Comment by damianlegawiec** [comment]
Hi @zavan could you create:
1. PR to https://github.com/spree/spree to fix the API route
2. and another PR to this repo to fix the JS code?

Thanks!

**Comment by zavan** [comment]
@damianlegawiec Done!
